---
- name: 'start httpd'
  service:
    name: httpd
    state: started

- name: 'restart httpd'
  service:
    name: httpd
    state: restarted

- name: 'restart iptables'
  service:
    name:  iptables
    state: restarted
