---
# handlers file for actions that are notified: by a play
- name: 'start postgresql-9.4'
  become: yes
  service: name=postgresql-9.4 state=started

- name: 'restart postgresql-9.4'
  become: yes
  service: name=postgresql-9.4 state=restarted
