---

- name: 'install the postgres yum repo'
  become: yes
  yum: name={{ postgres_repo }} state=present
  when: ansible_os_family == "RedHat"
  tags:
    - install

- name: 'install postgres packages'
  become: yes
  yum: name={{ item }} state=present
  with_items: '{{ postgres_packages }}'
  when: ansible_os_family == "RedHat"
  tags:
    - install
